// Seed presets for Natalia's three real strategy identities.
//
//   1. Freeballin Pro Auto v2.74 (6.24 base)   — automation lane #1
//   2. FREEBALLIN v17.9.15 (2.1.1 / 2.4)       — automation lane #2
//   3. Freeballin 20.87 — STOPS                 — manual (Trade Manager)
//
// Each carries the correct alert JSON envelope shape for the three
// broker webhook systems Pine emits:
//   · Pick My Trade (pmt) — entry with advance_tp_sl bracket + close + SL update
//   · TradersPost (tpost) — action:"buy/sell/exit" simple JSON
//   · Trade Engine (te)   — event: ENTRY / TPn / STOP_UPDATE / MASTER_CLOSE
//
// Copy-paste-ready. Placeholders wrapped in {{...}} the trader edits per
// account (token, account_id, TradersPost ticker, TE key).

export const SEED_STRATEGIES = [
  {
    key: "freeballin_pro_auto_v2_74_624",
    name: "Freeballin Pro Auto v2.74 — 6.24 base",
    kind: "automation",
    version: "v2.74 (6.24)",
    description: "Current live automation. mode624 switch ON, base entries only (REV/RUN off). duplicate_position_allow=false on ALL messages (entry/close/sl-update) — source-verified in pine/Freeballin_Pro_v2_74_624.pine.",
    default_symbol: "MNQ1!",
    tp_ladder: { tp1_rr: 0.5, tp2_rr: 1.0, tp3_rr: 2.2, runner: true, jump_ticks: 40 },
    trail: { start: "At TP1", type: "EMA-ATR", ema_len: 21, atr_mult: 1.0, buffer_ticks: 3 },
    creep: { on: false, start: "Entry", step_ticks: 1 },
    color_hint: "#3b82f6", // blue
    templates: {
      pmt_entry: {
        symbol: "{{PMT_SYMBOL}}",
        date: "{{TIMENOW}}",
        data: "{{buy_or_sell}}",
        quantity: 3,
        risk_percentage: 0,
        price: "{{ENTRY_PRICE}}",
        gtd_in_second: 0,
        stp_limit_stp_price: 0,
        update_tp: false,
        update_sl: false,
        breakeven_offset: 0,
        token: "{{PMT_TOKEN}}",
        pyramid: false,
        same_direction_ignore: false,
        reverse_order_close: false,
        duplicate_position_allow: false,
        order_type: "MKT",
        advance_tp_sl: [
          { quantity: 1, tp: "{{TP1}}", percentage_tp: 0, dollar_tp: 0, sl: "{{STOP}}", percentage_sl: 0, dollar_sl: 0, breakeven: 0, breakeven_offset: 0, trail: 0, trail_stop: 0, trail_trigger: 0, trail_freq: 0 },
          { quantity: 1, tp: "{{TP2}}", percentage_tp: 0, dollar_tp: 0, sl: "{{STOP}}", percentage_sl: 0, dollar_sl: 0, breakeven: 0, breakeven_offset: 0, trail: 0, trail_stop: 0, trail_trigger: 0, trail_freq: 0 },
          { quantity: 1, tp: 99999,     percentage_tp: 0, dollar_tp: 0, sl: "{{STOP}}", percentage_sl: 0, dollar_sl: 0, breakeven: 0, breakeven_offset: 0, trail: 0, trail_stop: 0, trail_trigger: 0, trail_freq: 0 },
        ],
        multiple_accounts: [{ token: "{{PMT_TOKEN}}", account_id: "{{ACCOUNT_ID}}", risk_percentage: 0, quantity_multiplier: 1 }],
      },
      pmt_close: {
        symbol: "{{PMT_SYMBOL}}",
        data: "CLOSE",
        quantity: 0,
        full_closed: true,
        token: "{{PMT_TOKEN}}",
        account_id: "{{ACCOUNT_ID}}",
        multiple_accounts: [{ token: "{{PMT_TOKEN}}", account_id: "{{ACCOUNT_ID}}", risk_percentage: 0, quantity_multiplier: 1 }],
        risk_percentage: 0.0,
        comment: "{{REASON}}",
        breakeven: 0,
        trail_stop: 0,
        trail_trigger: 0,
        trail_freq: 0,
        trail: 0,
        price: 0,
        tp: 0,
        stp_limit_stp_price: 0,
        sl: 0,
        main_token_type: "DEMO",
        duplicate_position_allow: false,
        order_type: null,
        dollar_tp: 0,
        dollar_sl: 0,
        reverse_order_close: false,
        update_tp: false,
        update_sl: false,
        percentage_tp: 0,
        percentage_sl: 0,
        same_direction_ignore: false,
        gtd_in_second: 0,
        date: "{{TIMENOW}}",
        reverse_action: false,
        created_first: "",
        strategy_name: "CLOSE ({{REASON}})",
        tif: "GTC",
        breakeven_offset: 0,
      },
      pmt_sl_update: {
        symbol: "{{PMT_SYMBOL}}",
        data: "{{buy_or_sell}}",
        quantity: "{{REM_QTY}}",
        update_sl: true,
        update_tp: false,
        sl: "{{NEW_STOP}}",
        token: "{{PMT_TOKEN}}",
        same_direction_ignore: false,
        duplicate_position_allow: false,
        account_id: "{{ACCOUNT_ID}}",
        multiple_accounts: [{ token: "{{PMT_TOKEN}}", account_id: "{{ACCOUNT_ID}}", risk_percentage: 0, quantity_multiplier: 1 }],
        strategy_name: "SL {{TAG}} (#{{SESSION_TAG}})",
      },
      tpost_entry:  { ticker: "{{TPOST_TICKER}}", action: "{{buy_or_sell}}", quantity: 3, quantityType: "fixed_quantity", orderType: "market" },
      tpost_exit:   { ticker: "{{TPOST_TICKER}}", action: "exit" },
      te_entry:     { event: "ENTRY", ticker: "{{PMT_SYMBOL}}", side: "{{LONG_or_SHORT}}", qty: 3, entry_px: 0, stop_px: 0, source: "Freeballin v2.74 6.24", key: "{{TE_KEY}}" },
    },
  },

  {
    key: "freeballin_v17_9_15_2_1_1_2_4",
    name: "FREEBALLIN v17.9.15 (params 2.1.1 / 2.4)",
    kind: "automation",
    version: "v17.9.15",
    description: "Older automation lane running v17.9.15 with param profile 2.1.1 / 2.4. Envelope DIFFERS from v2.74: entry omits duplicate_position_allow entirely; close sends duplicate_position_allow=true; SL-update uses same_direction_ignore=true and omits multiple_accounts. Source-verified in pine/Freeballin_Pro_v17_9_15_v2_1_1_v2_4.pine.",
    default_symbol: "MNQ1!",
    tp_ladder: { tp1_rr: 0.5, tp2_rr: 1.0, tp3_rr: 2.2, runner: true, jump_ticks: 0 },
    trail: { start: "At TP1", type: "EMA-ATR", ema_len: 21, atr_mult: 1.0, buffer_ticks: 3 },
    color_hint: "#8b5cf6", // purple
    templates: {
      pmt_entry: {
        symbol: "{{PMT_SYMBOL}}",
        date: "{{TIMENOW}}",
        data: "{{buy_or_sell}}",
        quantity: 10,
        risk_percentage: 0,
        price: "{{ENTRY_PRICE}}",
        gtd_in_second: 0,
        stp_limit_stp_price: 0,
        update_tp: false,
        update_sl: false,
        breakeven_offset: 0,
        token: "{{PMT_TOKEN}}",
        pyramid: false,
        same_direction_ignore: false,
        reverse_order_close: false,
        order_type: "MKT",
        advance_tp_sl: [
          { quantity: 3, tp: "{{TP1}}", percentage_tp: 0, dollar_tp: 0, sl: "{{STOP}}", percentage_sl: 0, dollar_sl: 0, breakeven: 0, breakeven_offset: 0, trail: 0, trail_stop: 0, trail_trigger: 0, trail_freq: 0 },
          { quantity: 4, tp: "{{TP2}}", percentage_tp: 0, dollar_tp: 0, sl: "{{STOP}}", percentage_sl: 0, dollar_sl: 0, breakeven: 0, breakeven_offset: 0, trail: 0, trail_stop: 0, trail_trigger: 0, trail_freq: 0 },
          { quantity: 2, tp: "{{TP3}}", percentage_tp: 0, dollar_tp: 0, sl: "{{STOP}}", percentage_sl: 0, dollar_sl: 0, breakeven: 0, breakeven_offset: 0, trail: 0, trail_stop: 0, trail_trigger: 0, trail_freq: 0 },
          { quantity: 1, tp: 99999,     percentage_tp: 0, dollar_tp: 0, sl: "{{STOP}}", percentage_sl: 0, dollar_sl: 0, breakeven: 0, breakeven_offset: 0, trail: 0, trail_stop: 0, trail_trigger: 0, trail_freq: 0 },
        ],
        multiple_accounts: [{ token: "{{PMT_TOKEN}}", account_id: "{{ACCOUNT_ID}}", risk_percentage: 0, quantity_multiplier: 1 }],
      },
      pmt_close: {
        symbol: "{{PMT_SYMBOL}}",
        data: "CLOSE",
        quantity: 0,
        full_closed: true,
        token: "{{PMT_TOKEN}}",
        account_id: "{{ACCOUNT_ID}}",
        risk_percentage: 0.0,
        comment: "",
        breakeven: 0,
        trail_stop: 0,
        trail_trigger: 0,
        trail_freq: 0,
        trail: 0,
        price: 0,
        tp: 0,
        stp_limit_stp_price: 0,
        sl: 0,
        main_token_type: "DEMO",
        duplicate_position_allow: true,
        order_type: null,
        dollar_tp: 0,
        dollar_sl: 0,
        reverse_order_close: false,
        update_tp: false,
        update_sl: false,
        percentage_tp: 0,
        percentage_sl: 0,
        same_direction_ignore: false,
        gtd_in_second: 0,
        date: "{{TIMENOW}}",
        reverse_action: false,
        created_first: "",
        strategy_name: "",
        tif: "GTC",
        breakeven_offset: 0,
      },
      pmt_sl_update: {
        symbol: "{{PMT_SYMBOL}}",
        data: "{{buy_or_sell}}",
        quantity: 10,
        update_sl: true,
        update_tp: false,
        sl: "{{NEW_STOP}}",
        token: "{{PMT_TOKEN}}",
        same_direction_ignore: true,
        account_id: "{{ACCOUNT_ID}}",
      },
      tpost_entry: { ticker: "{{TPOST_TICKER}}", action: "{{buy_or_sell}}", sentiment: "{{bullish_or_bearish}}", quantity: 10, quantityType: "fixed_quantity", orderType: "market", stopLoss: { type: "stop", stopPrice: "{{STOP}}" } },
      tpost_exit:  { ticker: "{{TPOST_TICKER}}", action: "exit" },
      tpost_cancel:{ ticker: "{{TPOST_TICKER}}", action: "cancel" },
      te_entry:    { event: "ENTRY", ticker: "{{PMT_SYMBOL}}", side: "{{LONG_or_SHORT}}", qty: 10, source: "FREEBALLIN v17.9.15", key: "{{TE_KEY}}" },
    },
  },

  {
    key: "tm_v20_87_stops",
    name: "TM v20.87 — STOPS (manual)",
    kind: "manual",
    version: "v20.87",
    description: "Manual Trade Manager — you drag entry/stop, indicator sends webhooks. LIVE mode, PMT + TPOST + TE all supported. BE update fires at TP1 %; Creep + Trail default to CLOSE-on-hit; safety stop lives at broker until stop_hit or master_close.",
    default_symbol: "MNQ1!",
    tp_ladder: { tp1_rr: 1.0, tp2_rr: 2.0, tp3_rr: 3.0, runner: true, jump_ticks: 40 },
    color_hint: "#10b981", // emerald
    templates: {
      pmt_entry: {
        symbol: "{{PMT_SYMBOL}}",
        date: "{{TIMENOW}}",
        data: "{{buy_or_sell}}",
        quantity: 4,
        price: "{{ENTRY_FILL_PX}}",
        order_type: "MKT",
        token: "{{PMT_TOKEN}}",
        pyramid: false,
        same_direction_ignore: false,
        reverse_order_close: false,
        advance_tp_sl: [
          { quantity: 1, tp: "{{TP1}}", sl: "{{STOP}}" },
          { quantity: 1, tp: "{{TP2}}", sl: "{{STOP}}" },
          { quantity: 1, tp: "{{TP3}}", sl: "{{STOP}}" },
          { quantity: 1, tp: 99999,       sl: "{{STOP}}" },
        ],
        multiple_accounts: [{ token: "{{PMT_TOKEN}}", account_id: "{{ACCOUNT_ID}}", risk_percentage: 0, quantity_multiplier: 1 }],
      },
      pmt_close_50: {
        symbol: "{{PMT_SYMBOL}}",
        data: "{{sell_or_buy}}",
        quantity: "{{HALF_QTY}}",
        token: "{{PMT_TOKEN}}",
        multiple_accounts: [{ token: "{{PMT_TOKEN}}", account_id: "{{ACCOUNT_ID}}", risk_percentage: 0, quantity_multiplier: 1 }],
      },
      pmt_master_close: {
        symbol: "{{PMT_SYMBOL}}",
        data: "CLOSE",
        quantity: 0,
        full_closed: true,
        token: "{{PMT_TOKEN}}",
        account_id: "{{ACCOUNT_ID}}",
        duplicate_position_allow: true,
      },
      pmt_sl_update: {
        symbol: "{{PMT_SYMBOL}}",
        data: "{{buy_or_sell}}",
        quantity: "{{REM_CT}}",
        update_sl: true,
        update_tp: false,
        sl: "{{NEW_STOP}}",
        token: "{{PMT_TOKEN}}",
        same_direction_ignore: true,
        account_id: "{{ACCOUNT_ID}}",
        strategy_name: "SL BE",
      },
      tpost_entry:  { ticker: "{{TPOST_TICKER}}", action: "{{buy_or_sell}}", quantity: 4, quantityType: "fixed_quantity", orderType: "market", signalPrice: "{{ENTRY_FILL_PX}}", time: "{{TIMENOW}}" },
      tpost_safety_stop: { ticker: "{{TPOST_TICKER}}", action: "{{sell_or_buy}}", orderType: "stop", stopPrice: "{{STOP}}", quantity: 4, quantityType: "fixed_quantity" },
      tpost_tp_partial: { ticker: "{{TPOST_TICKER}}", action: "exit", quantity: 1, quantityType: "fixed_quantity", orderType: "market" },
      tpost_close_50: { ticker: "{{TPOST_TICKER}}", action: "exit", quantityType: "percent_of_position", quantity: 50 },
      tpost_full_exit: { ticker: "{{TPOST_TICKER}}", action: "exit" },
      te_entry: {
        event: "ENTRY", ticker: "{{PMT_SYMBOL}}", side: "{{LONG_or_SHORT}}", qty: 4,
        entry_px: "{{ENTRY_FILL_PX}}", stop_px: "{{STOP}}",
        tp1_px: "{{TP1}}", tp1_qty: 1,
        tp2_px: "{{TP2}}", tp2_qty: 1,
        tp3_px: "{{TP3}}", tp3_qty: 1,
        runner_qty: 1,
        source: "Freeballin 20.87 — STOPS",
        key: "{{TE_KEY}}",
      },
      te_master_close: { event: "MASTER_CLOSE", ticker: "{{PMT_SYMBOL}}", close_qty: "{{REM_CT}}", remaining_qty: 0, key: "{{TE_KEY}}" },
    },
  },
];

// Bulk-seed helper — returns the shape the Strategy.create endpoint
// expects. Each strategy stores its templates as a `json_templates`
// object on the row so the alert-JSON dialog can render one card per
// event type without needing hardcoded knowledge of each strategy.
export function seedRowFor(preset) {
  return {
    name: preset.name,
    description: preset.description,
    default_symbol: preset.default_symbol,
    kind: preset.kind,
    version_tag: preset.version,
    color_hint: preset.color_hint,
    tp_ladder: JSON.stringify(preset.tp_ladder),
    trail:     preset.trail ? JSON.stringify(preset.trail) : null,
    creep:     preset.creep ? JSON.stringify(preset.creep) : null,
    json_templates: JSON.stringify(preset.templates, null, 2),
  };
}
